### ISSUE TITLE
How to select the kev-script with -Dnode.bootstrap?

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/ApamaComponents#13]
@maxleiko , according to https://github.com/dukeboard/kevoree/wiki/Kevoree-System-Properties the following should work, but I get the following error. Kevoree searches for src\main\kevs\main.kevs

C:\Workspaces\HEADS ATC Use Case\kevoreeNewsAssetCep>mvn kev:run -Dnode.bootstrap=src/main/kevs/inject.kevs
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building News Asset CEP Kevoree Scripts to run ApamaComponents 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- org.kevoree.tools.mavenplugin:5.4.0-SNAPSHOT:run (default-cli) @ kevoreeNewsAssetCep ---
[INFO] Generating a Kevoree model by reflection...
[INFO] Model saved at target\classes\KEV-INF\kevlib.json
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.388 s
[INFO] Finished at: 2017-01-11T19:29:46+01:00
[INFO] Final Memory: 10M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.kevoree.tools:org.kevoree.tools.mavenplugin:5.4.0-SNAPSHOT:run (default-cli) on project kevoreeNewsAssetCep: Unable
 to read KevScript file at src\main\kevs\main.kevs: C:\Workspaces\HEADS ATC Use Case\kevoreeNewsAssetCep\src\main\kevs\main.kevs -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by maxleiko** [comment]
@skorsky you are using the Maven plugin to start Kevoree. Not the executable `.jar`.  
When using the Maven plugin, you should configure the path to the KevScript using the `pom.xml`.  
Because it is convenient to override that value from the command-line, you can specify:

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.kevoree.tools</groupId>
                <artifactId>org.kevoree.tools.mavenplugin</artifactId>
                <version>${kevoree.version}</version>
                <configuration>
                    <namespace>yournamespacehere</namespace>
                    <kevscript>${env.KEVS}</kevscript>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

By doing so, you can override the kevscript file using an environment variable:

```sh
KEVS=/some/path/to/your.kevs mvn kev:run
```

The cool thing is that by default, if you do no have the `KEVS` var defined, then it will default to the proper `src/main/kevs/main.kevs` file  

If you want more Maven [readings](http://books.sonatype.com/mvnref-book/reference/resource-filtering-sect-properties.html)
