### ISSUE TITLE
Description of .kevoree/config.json

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/ApamaComponents#7]
Is there some documentation on .kevoree/config.json?
Should the .kevoree folder be in the user's home?
Is it allowed to configure more than one Kevoree repository in this file?

**Comment by maxleiko** [comment]
**Is there some documentation on .kevoree/config.json?**
The presentation I've made in Paris should be in the eRoom.  
But I will also add a section on that in the [Kevoree book](http://book.kevoree.org) as soon as it goes to a proper release version.
```json
{
  "user": {
    "login": "yourUsername",
    "password": "yourPassword"
  },
  "registry": {
    "host": "kevoree.braindead.fr",
    "port": 443,
    "ssl": true,
    "oauth": {
      "client_secret": "kevoree_registryapp_secret",
      "client_id": "kevoree_registryapp"
    }
  }
}
```

For now this is everything a `config.json` file uses.  
Note that the `user` part is not needed if you are not going to publish libraries on the Kevoree Registry. 

**Should the .kevoree folder be in the user's home?** 
Yes.

**Is it allowed to configure more than one Kevoree repository in this file?**
No.
