### ISSUE TITLE
Kevoree resolves to older artifacts

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/ApamaComponents#8]
With mvn clean install I get older artifacts from a Kevoree registry. Source changes are not reflected. The local Maven repository contains the newest version of the artifact, but this is not used during mvn kev:run.

Is there a merge between repositories in .m2/setting.xml and .kevoree/config.json?

**Comment by maxleiko** [comment]
The Kevoree registry is not a Maven repository. So there is no merge of the two files as they are not doing the same job.
